### ISSUE TITLE
Exception Caused by: java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by vincenzopalazzo** [clightning4j/btcli4j#1]
The backend can have a problem and generate some exception like this

```
2020-09-03T09:41:51.650Z UNUSUAL plugin-btcli4j.sh: {\"id\":328,\"jsonrpc\":\"2.0\",\"result\":{\"blockhash\":null,\"block\":null}}
2020-09-03T09:42:06.521Z UNUSUAL plugin-btcli4j.sh: Request: {\"jsonrpc\":\"2.0\",\"id\":329,\"method\":\"estimatefees\",\"params\":{}}
2020-09-03T09:42:06.521Z UNUSUAL plugin-btcli4j.sh: estimatefees
2020-09-03T09:42:06.522Z DEBUG plugin-btcli4j.sh: Method estimatefees found
2020-09-03T09:42:11.026Z DEBUG gossipd: seeker: no peers, waiting
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at jrpc.clightning.plugins.rpcmethods.RPCMethodReflection.doRun(RPCMethodReflection.java:33)
	at jrpc.clightning.plugins.CLightningPlugin.doMethods(CLightningPlugin.java:279)
	at jrpc.clightning.plugins.CLightningPlugin.start(CLightningPlugin.java:127)
	at io.vincenzopalazzo.btcli4j.AppKt.main(App.kt:9)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.vincenzopalazzo.btcli4j.util.HttpRequestFactory.execRequest(HttpRequestFactory.kt:26)
	at io.vincenzopalazzo.btcli4j.control.commands.EstimateFeeCommand.run(EstimateFeeCommand.kt:18)
	at io.vincenzopalazzo.btcli4j.control.MediationMethod.runCommand(MediationMethod.kt:27)
	at io.vincenzopalazzo.btcli4j.Plugin.estimateFees(Plugin.kt:17)
	... 7 more
```

**Comment by vincenzopalazzo** [comment]
This looked like a bug with HttpRequestFactory, for the moment I fixed it
