### ISSUE TITLE
Another some strange exception with the stream

### ISSUE THREAD

**Issue by vincenzopalazzo** [clightning4j/btcli4j#13]
```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at jrpc.clightning.plugins.rpcmethods.RPCMethodReflection.doRun(RPCMethodReflection.java:31)
	at jrpc.clightning.plugins.CLightningPlugin.doMethods(CLightningPlugin.java:284)
	at jrpc.clightning.plugins.CLightningPlugin.start(CLightningPlugin.java:129)
	at io.vincenzopalazzo.btcli4j.AppKt.main(App.kt:26)
Caused by: jrpc.clightning.plugins.exceptions.CLightningPluginException: stream was reset: INTERNAL_ERROR
	at io.vincenzopalazzo.btcli4j.control.commands.GetRawBlockByHeightCommand.run(GetRawBlockByHeightCommand.kt:64)
	at io.vincenzopalazzo.btcli4j.control.MediationMethod.runCommand(MediationMethod.kt:44)
	at io.vincenzopalazzo.btcli4j.Plugin.getRawBlockByHeight(Plugin.kt:65)
	... 7 more

```

**Comment by vincenzopalazzo** [comment]
This looks like a server exception (look [here](https://stackoverflow.com/questions/65137191/okhttp-keeps-getting-streamresetexception-stream-was-reset-internal-error-when)) and maybe this can be linked with this problem https://github.com/lightningamp/esplora_clnd_plugin/issues

**Comment by vincenzopalazzo** [comment]
This looks like a server error as described inside this issue here https://stackoverflow.com/a/65139765/10854225
