### ISSUE TITLE
Client crash with internet error

### ISSUE THREAD

**Issue by vincenzopalazzo** [clightning4j/btcli4j#25]
Sometimes the client can crash (error crash) and this can happen on a normal computer with a poor connection

This I the log that I receive from the test
```

**2021-03-19T07:08:16.296Z **BROKEN** plugin-btcli4j-gen.sh: Message empty
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at jrpc.clightning.plugins.rpcmethods.RPCMethodReflection.doRun(RPCMethodReflection.java:31)
	at jrpc.clightning.plugins.CLightningPlugin.doMethods(CLightningPlugin.java:283)
	at jrpc.clightning.plugins.CLightningPlugin.start(CLightningPlugin.java:128)
	at io.vincenzopalazzo.btcli4j.AppKt.main(App.kt:26)
	at io.vincenzopalazzo.btcli4j.AppKt.main(App.kt)
Caused by: jrpc.clightning.plugins.exceptions.CLightningPluginException: java.net.SocketException: Socket closed
	at io.vincenzopalazzo.btcli4j.control.commands.GetRawBlockByHeightCommand.run(GetRawBlockByHeightCommand.kt:66)
	at io.vincenzopalazzo.btcli4j.control.MediationMethod.runCommand(MediationMethod.kt:49)
	at io.vincenzopalazzo.btcli4j.Plugin.getRawBlockByHeight(Plugin.kt:73)
	... 8 more
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:982)
	at okio.InputStreamSource.read(JvmOkio.kt:90)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.vincenzopalazzo.btcli4j.util.HttpRequestFactory.makeRequest(HttpRequestFactory.kt:144)
	at io.vincenzopalazzo.btcli4j.util.HttpRequestFactory.execRequest(HttpRequestFactory.kt:104)
	at io.vincenzopalazzo.btcli4j.control.commands.GetRawBlockByHeightCommand.run(GetRawBlockByHeightCommand.kt:42)
	... 10 more
/home/vincent/Github/btcli4j/btcli4j-gen.sh error: bad response to getrawblockbyheight (bad 'result' field: Parsing '{result:{blockhash:': object does not have member blockhash), response was {"id":2651,"jsonrpc":"2.0","result":{}}
2021-03-19T07:08:16.309Z **BROKEN** lightningd: /home/vincent/Github/btcli4j/btcli4j-gen.sh error: bad response to getrawblockbyheight (bad 'result' field: Parsing '{result:{blockhash:': object does not have member blockhash), response was {"id":2651,"jsonrpc":"2.0","result":{}}
lightningd: FATAL SIGNAL 6 (version 0.9.3)
**
```

**Comment by vincenzopalazzo** [comment]
Fixed https://github.com/clightning4j/btcli4j/commit/d5686bbd76227c1a262887f2518422d28d61c38c
