### ISSUE TITLE
Simple install only leads to errors

### ISSUE THREAD

**Issue by d4amenace** [clightning4j/btcli4j#48]
Hello,

I followed these steps to install the plugin:

- sudo apt install default-jdk
- javac --version
- install this to whatever directory I like…. git clone https://github.com/clightning4j/btcli4j.git
- cd btcli4j
- ./gradlew createRunnableScript
- now in this directory you have a file called btcli4j-gen.sh
- Put the absolute path in the lightning config file (plugin=/home/nextlayer/btcli4j/btcli4j-gen.sh
- Now you can run lightning with the new cmd: lightningd --disable-plugin bcli

But when I do I get this.....................

```
lightningd --disable-plugin bcli
Exception in thread "main" java.lang.IllegalArgumentException: Can not set int field io.vincenzopalazzo.btcli4j.Plugin.waitingTime to java.lang.String
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at java.base/jdk.internal.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:98)
        at java.base/java.lang.reflect.Field.set(Field.java:780)
        at jrpc.clightning.plugins.interceptor.MappingCmdOptions.doAction(MappingCmdOptions.java:35)
        at jrpc.clightning.plugins.CLightningPlugin.lambda$doMethods$1(CLightningPlugin.java:383)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at jrpc.clightning.plugins.CLightningPlugin.doMethods(CLightningPlugin.java:381)
        at jrpc.clightning.plugins.CLightningPlugin.start(CLightningPlugin.java:168)
        at io.vincenzopalazzo.btcli4j.AppKt.main(App.kt:26)
        at io.vincenzopalazzo.btcli4j.AppKt.main(App.kt)
The Bitcoin backend died.
```

**Comment by d4amenace** [comment]
Could it be because I installed this plugin to another lightning node at the same ip address on a different server?  Is it possible there are hardware conflicts?

**Comment by vincenzopalazzo** [comment]
Unfortunately, this is caused by an old version of c-lightning, we don't support the old version (after 6 months lightning break the API) if you will update to one of the last versions, your node will be up and running again.

I will leave this issue open for a couple of that, after that if any update happens, I will close.

Thanks

**Comment by d4amenace** [comment]
Yes, a mistake was made in not updating the node.
